# [코드리뷰 프로젝트] 2. 경사하강법 구현

## 1. 경사하강법
- 선형 회귀 모델을 구현하기 위한 데이터를 확인하고, 알맞은 형태로 분리합니다.
- 분리한 데이터를 활용해 train, weight, bias를 정의합니다.
- 경사하강법 구현을 위한 학습 루프를 만들고, 100회 반복해 결과를 출력합니다.

### [TODO] 1_ 데이터 분리

In [1]:
# 미션 : 아래와 같은 출력 결과가 나타나도록 코드를 작성해보세요.

##############################################
#### 코드리뷰 2-1. 알맞은 코드를 직접 작성해보세요! ####
##############################################

# 프로그램 실행 예시
# 출력 결과

# print(x_train, x_train.shape)
# [1. 2. 3. 4. 5. 6.] (6,)

# print(y_train, y_train.shape)
# [10. 20. 30. 40. 50. 60.] (6,)


import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.],
               [10., 20., 30., 40., 50., 60.]])

## 코드시작 ##
x_train = xy[0]    
y_train = xy[1]   
## 코드종료 ##

print(x_train, x_train.shape)
print(y_train, y_train.shape)


[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


### [TODO] 2_ train, weight, bias 정의

In [ ]:
# 미션 : 아래와 같은 출력 결과가 나타나도록 코드를 작성해보세요.

##############################################
#### 코드리뷰 2-2. 알맞은 코드를 직접 작성해보세요! ####
##############################################

# 프로그램 실행 예시
# 출력 결과

# print(beta_gd, bias)
# [0.53764546] [0.71495179]    # randoma을 사용해 숫자를 만들어냈기 때문에, 출력결과는 다를 수 있습니다. 형태 위주로 확인해주세요.

In [3]:
## 코드시작 ##

np.random.seed(0)

beta_gd = np.random.rand(1) 
bias = np.random.rand(1)

## 코드종료 ##

print(beta_gd, bias)

[0.5488135] [0.71518937]


### [TODO] 3_ 경사하강법 구현

In [6]:
# 미션 : 위와 같은 출력 결과가 나타나도록 코드를 작성해보세요.

##############################################
#### 코드리뷰 2-3. 알맞은 코드를 직접 작성해보세요! ####
##############################################

np.random.seed(0)
beta_gd = np.random.rand(1)
bias = np.random.rand(1)

# 다양한 학습률 설정
learning_rates = [0.001, 0.01, 0.1]

# 결과 저장
results = []

for lr in learning_rates:
    # 파라미터 초기화
    beta_gd = beta_gd.copy()
    bias = bias.copy()
    
    # 학습
    for i in range(1000):
        pred = beta_gd * x_train + bias
        error = ((pred - y_train) ** 2).mean()

        gd_w = ((pred - y_train) * 2 * x_train).mean()
        gd_b = ((pred - y_train) * 2).mean()

        beta_gd -= lr * gd_w
        bias -= lr * gd_b

        if i % 100 == 0:
            print(f'Learning Rate: {lr} | Epoch {i:4d}/1000 | Cost: {error:.6f} | w: {beta_gd.item():.6f} | b: {bias.item():.6f}')

    # 최종 비용 저장
    results.append((lr, error, beta_gd.item(), bias.item()))

# 결과 출력
for lr, final_error, final_beta, final_bias in results:
    print(f'Learning Rate: {lr} | Final Cost: {final_error:.6f} | Final w: {final_beta:.6f} | Final b: {final_bias:.6f}')


Learning Rate: 0.001 | Epoch    0/1000 | Cost: 1307.957160 | w: 0.830493 | b: 0.779917
Learning Rate: 0.001 | Epoch  100/1000 | Cost: 3.342027 | w: 9.045288 | b: 2.594001
Learning Rate: 0.001 | Epoch  200/1000 | Cost: 1.280321 | w: 9.385576 | b: 2.572516
Learning Rate: 0.001 | Epoch  300/1000 | Cost: 1.187434 | w: 9.419477 | b: 2.483084
Learning Rate: 0.001 | Epoch  400/1000 | Cost: 1.103833 | w: 9.440746 | b: 2.394191
Learning Rate: 0.001 | Epoch  500/1000 | Cost: 1.026122 | w: 9.460809 | b: 2.308380
Learning Rate: 0.001 | Epoch  600/1000 | Cost: 0.953882 | w: 9.480136 | b: 2.225641
Learning Rate: 0.001 | Epoch  700/1000 | Cost: 0.886727 | w: 9.498769 | b: 2.145868
Learning Rate: 0.001 | Epoch  800/1000 | Cost: 0.824301 | w: 9.516735 | b: 2.068954
Learning Rate: 0.001 | Epoch  900/1000 | Cost: 0.766269 | w: 9.534057 | b: 1.994796
Learning Rate: 0.01 | Epoch    0/1000 | Cost: 0.712323 | w: 9.552233 | b: 1.916978
Learning Rate: 0.01 | Epoch  100/1000 | Cost: 0.342855 | w: 9.689352 | b: 

C:\Users\defy2\AppData\Local\Temp\ipykernel_4124\3257767725.py:25: RuntimeWarning: overflow encountered in square
  error = ((pred - y_train) ** 2).mean()
C:\Users\defy2\AppData\Local\Temp\ipykernel_4124\3257767725.py:30: RuntimeWarning: invalid value encountered in subtract
  beta_gd -= lr * gd_w


ALL RIGHTS RESERVED. (C)NAVER Connect Foundation.